// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: repogo/v1/preview_gateway.proto

package previewgatewayv1

import (
	preview "github.com/repogo/host/internal/tunnel/wire/preview"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Device → gateway.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_HttpResponse
	//	*ClientMessage_HttpBodyChunk
	//	*ClientMessage_WsOpenAck
	//	*ClientMessage_WsFrame
	//	*ClientMessage_WsClose
	//	*ClientMessage_Proof
	Body          isClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetBody() isClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetHello() *DeviceHello {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetHttpBodyChunk() *preview.PreviewBodyChunk {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_HttpBodyChunk); ok {
			return x.HttpBodyChunk
		}
	}
	return nil
}

func (x *ClientMessage) GetWsOpenAck() *WsOpenAck {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_WsOpenAck); ok {
			return x.WsOpenAck
		}
	}
	return nil
}

func (x *ClientMessage) GetWsFrame() *preview.PreviewWsFrame {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_WsFrame); ok {
			return x.WsFrame
		}
	}
	return nil
}

func (x *ClientMessage) GetWsClose() *preview.PreviewWsClose {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_WsClose); ok {
			return x.WsClose
		}
	}
	return nil
}

func (x *ClientMessage) GetProof() *HostProof {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Proof); ok {
			return x.Proof
		}
	}
	return nil
}

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Hello struct {
	Hello *DeviceHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,2,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type ClientMessage_HttpBodyChunk struct {
	HttpBodyChunk *preview.PreviewBodyChunk `protobuf:"bytes,3,opt,name=http_body_chunk,json=httpBodyChunk,proto3,oneof"`
}

type ClientMessage_WsOpenAck struct {
	WsOpenAck *WsOpenAck `protobuf:"bytes,4,opt,name=ws_open_ack,json=wsOpenAck,proto3,oneof"`
}

type ClientMessage_WsFrame struct {
	WsFrame *preview.PreviewWsFrame `protobuf:"bytes,5,opt,name=ws_frame,json=wsFrame,proto3,oneof"`
}

type ClientMessage_WsClose struct {
	WsClose *preview.PreviewWsClose `protobuf:"bytes,6,opt,name=ws_close,json=wsClose,proto3,oneof"`
}

type ClientMessage_Proof struct {
	Proof *HostProof `protobuf:"bytes,7,opt,name=proof,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Body() {}

func (*ClientMessage_HttpResponse) isClientMessage_Body() {}

func (*ClientMessage_HttpBodyChunk) isClientMessage_Body() {}

func (*ClientMessage_WsOpenAck) isClientMessage_Body() {}

func (*ClientMessage_WsFrame) isClientMessage_Body() {}

func (*ClientMessage_WsClose) isClientMessage_Body() {}

func (*ClientMessage_Proof) isClientMessage_Body() {}

// Gateway → device.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Ready
	//	*ServerMessage_HttpRequest
	//	*ServerMessage_WsOpen
	//	*ServerMessage_WsFrame
	//	*ServerMessage_WsClose
	//	*ServerMessage_Challenge
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ServerMessage) GetHttpRequest() *preview.PreviewRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetWsOpen() *preview.PreviewWsOpen {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_WsOpen); ok {
			return x.WsOpen
		}
	}
	return nil
}

func (x *ServerMessage) GetWsFrame() *preview.PreviewWsFrame {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_WsFrame); ok {
			return x.WsFrame
		}
	}
	return nil
}

func (x *ServerMessage) GetWsClose() *preview.PreviewWsClose {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_WsClose); ok {
			return x.WsClose
		}
	}
	return nil
}

func (x *ServerMessage) GetChallenge() *HostChallenge {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Ready struct {
	Ready *Ready `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type ServerMessage_HttpRequest struct {
	HttpRequest *preview.PreviewRequest `protobuf:"bytes,2,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type ServerMessage_WsOpen struct {
	WsOpen *preview.PreviewWsOpen `protobuf:"bytes,3,opt,name=ws_open,json=wsOpen,proto3,oneof"`
}

type ServerMessage_WsFrame struct {
	WsFrame *preview.PreviewWsFrame `protobuf:"bytes,4,opt,name=ws_frame,json=wsFrame,proto3,oneof"`
}

type ServerMessage_WsClose struct {
	WsClose *preview.PreviewWsClose `protobuf:"bytes,5,opt,name=ws_close,json=wsClose,proto3,oneof"`
}

type ServerMessage_Challenge struct {
	Challenge *HostChallenge `protobuf:"bytes,6,opt,name=challenge,proto3,oneof"`
}

func (*ServerMessage_Ready) isServerMessage_Body() {}

func (*ServerMessage_HttpRequest) isServerMessage_Body() {}

func (*ServerMessage_WsOpen) isServerMessage_Body() {}

func (*ServerMessage_WsFrame) isServerMessage_Body() {}

func (*ServerMessage_WsClose) isServerMessage_Body() {}

func (*ServerMessage_Challenge) isServerMessage_Body() {}

// First ClientMessage on every stream. Identifies the device. No token —
// authorization is enforced by the Redis registry at request-time, not at
// connect-time.
type DeviceHello struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// A v2 host's raw Ed25519 public key. When set, user_id and device_id are
	// ignored: the gateway answers with a HostChallenge, and after a valid
	// HostProof registers the stream as `host:<id>`, the id derived from this
	// key. Unset is a v1 Mac and takes the path above unchanged.
	PublicKey     []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHello) Reset() {
	*x = DeviceHello{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHello) ProtoMessage() {}

func (x *DeviceHello) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHello.ProtoReflect.Descriptor instead.
func (*DeviceHello) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceHello) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceHello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHello) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Sent instead of Ready to a hello carrying public_key.
type HostChallenge struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Nonce     []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GatewayId string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// Unix milliseconds; signed, so a proof is bound to this one challenge.
	Time          uint64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostChallenge) Reset() {
	*x = HostChallenge{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostChallenge) ProtoMessage() {}

func (x *HostChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostChallenge.ProtoReflect.Descriptor instead.
func (*HostChallenge) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HostChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *HostChallenge) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *HostChallenge) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// Ed25519 over "repogo-tunnel/1|" + nonce + "|" + gateway_id + "|" + decimal time.
type HostProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostProof) Reset() {
	*x = HostProof{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostProof) ProtoMessage() {}

func (x *HostProof) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostProof.ProtoReflect.Descriptor instead.
func (*HostProof) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *HostProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Sent by the gateway after a successful Hello. Stream is now eligible to
// receive `http_request` / `ws_open` pushes.
type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{5}
}

// Echoed back by the device in response to a `http_request`. PreviewResponse
// itself has no session_id field (it was historically returned as an Emit
// Ack), so the wrapper carries the correlation id.
type HttpResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	SessionId     string                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Response      *preview.PreviewResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *HttpResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HttpResponse) GetResponse() *preview.PreviewResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

// Echoed back by the device in response to a `ws_open` push. Same reason
// as HttpResponse — PreviewWsOpenAck has no session_id field.
type WsOpenAck struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	SessionId     string                    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ack           *preview.PreviewWsOpenAck `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsOpenAck) Reset() {
	*x = WsOpenAck{}
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsOpenAck) ProtoMessage() {}

func (x *WsOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsOpenAck.ProtoReflect.Descriptor instead.
func (*WsOpenAck) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *WsOpenAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WsOpenAck) GetAck() *preview.PreviewWsOpenAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

var File_repogo_v1_preview_gateway_proto protoreflect.FileDescriptor

const file_repogo_v1_preview_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1frepogo/v1/preview_gateway.proto\x12\x19repogo.v1.preview_gateway\x1a\x17repogo/v1/preview.proto\"\xfc\x03\n" +
	"\rClientMessage\x12>\n" +
	"\x05hello\x18\x01 \x01(\v2&.repogo.v1.preview_gateway.DeviceHelloH\x00R\x05hello\x12N\n" +
	"\rhttp_response\x18\x02 \x01(\v2'.repogo.v1.preview_gateway.HttpResponseH\x00R\fhttpResponse\x12M\n" +
	"\x0fhttp_body_chunk\x18\x03 \x01(\v2#.repogo.v1.preview.PreviewBodyChunkH\x00R\rhttpBodyChunk\x12F\n" +
	"\vws_open_ack\x18\x04 \x01(\v2$.repogo.v1.preview_gateway.WsOpenAckH\x00R\twsOpenAck\x12>\n" +
	"\bws_frame\x18\x05 \x01(\v2!.repogo.v1.preview.PreviewWsFrameH\x00R\awsFrame\x12>\n" +
	"\bws_close\x18\x06 \x01(\v2!.repogo.v1.preview.PreviewWsCloseH\x00R\awsClose\x12<\n" +
	"\x05proof\x18\a \x01(\v2$.repogo.v1.preview_gateway.HostProofH\x00R\x05proofB\x06\n" +
	"\x04body\"\xa0\x03\n" +
	"\rServerMessage\x128\n" +
	"\x05ready\x18\x01 \x01(\v2 .repogo.v1.preview_gateway.ReadyH\x00R\x05ready\x12F\n" +
	"\fhttp_request\x18\x02 \x01(\v2!.repogo.v1.preview.PreviewRequestH\x00R\vhttpRequest\x12;\n" +
	"\aws_open\x18\x03 \x01(\v2 .repogo.v1.preview.PreviewWsOpenH\x00R\x06wsOpen\x12>\n" +
	"\bws_frame\x18\x04 \x01(\v2!.repogo.v1.preview.PreviewWsFrameH\x00R\awsFrame\x12>\n" +
	"\bws_close\x18\x05 \x01(\v2!.repogo.v1.preview.PreviewWsCloseH\x00R\awsClose\x12H\n" +
	"\tchallenge\x18\x06 \x01(\v2(.repogo.v1.preview_gateway.HostChallengeH\x00R\tchallengeB\x06\n" +
	"\x04body\"b\n" +
	"\vDeviceHello\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"X\n" +
	"\rHostChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x04R\x04time\")\n" +
	"\tHostProof\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"\a\n" +
	"\x05Ready\"m\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\bresponse\x18\x02 \x01(\v2\".repogo.v1.preview.PreviewResponseR\bresponse\"a\n" +
	"\tWsOpenAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\x03ack\x18\x02 \x01(\v2#.repogo.v1.preview.PreviewWsOpenAckR\x03ack2s\n" +
	"\x0ePreviewGateway\x12a\n" +
	"\aConnect\x12(.repogo.v1.preview_gateway.ClientMessage\x1a(.repogo.v1.preview_gateway.ServerMessage(\x010\x01BVZTgithub.com/repogo/preview-gateway-fly/gen/repogo/v1/preview_gateway;previewgatewayv1b\x06proto3"

var (
	file_repogo_v1_preview_gateway_proto_rawDescOnce sync.Once
	file_repogo_v1_preview_gateway_proto_rawDescData []byte
)

func file_repogo_v1_preview_gateway_proto_rawDescGZIP() []byte {
	file_repogo_v1_preview_gateway_proto_rawDescOnce.Do(func() {
		file_repogo_v1_preview_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repogo_v1_preview_gateway_proto_rawDesc), len(file_repogo_v1_preview_gateway_proto_rawDesc)))
	})
	return file_repogo_v1_preview_gateway_proto_rawDescData
}

var file_repogo_v1_preview_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_repogo_v1_preview_gateway_proto_goTypes = []any{
	(*ClientMessage)(nil),            // 0: repogo.v1.preview_gateway.ClientMessage
	(*ServerMessage)(nil),            // 1: repogo.v1.preview_gateway.ServerMessage
	(*DeviceHello)(nil),              // 2: repogo.v1.preview_gateway.DeviceHello
	(*HostChallenge)(nil),            // 3: repogo.v1.preview_gateway.HostChallenge
	(*HostProof)(nil),                // 4: repogo.v1.preview_gateway.HostProof
	(*Ready)(nil),                    // 5: repogo.v1.preview_gateway.Ready
	(*HttpResponse)(nil),             // 6: repogo.v1.preview_gateway.HttpResponse
	(*WsOpenAck)(nil),                // 7: repogo.v1.preview_gateway.WsOpenAck
	(*preview.PreviewBodyChunk)(nil), // 8: repogo.v1.preview.PreviewBodyChunk
	(*preview.PreviewWsFrame)(nil),   // 9: repogo.v1.preview.PreviewWsFrame
	(*preview.PreviewWsClose)(nil),   // 10: repogo.v1.preview.PreviewWsClose
	(*preview.PreviewRequest)(nil),   // 11: repogo.v1.preview.PreviewRequest
	(*preview.PreviewWsOpen)(nil),    // 12: repogo.v1.preview.PreviewWsOpen
	(*preview.PreviewResponse)(nil),  // 13: repogo.v1.preview.PreviewResponse
	(*preview.PreviewWsOpenAck)(nil), // 14: repogo.v1.preview.PreviewWsOpenAck
}
var file_repogo_v1_preview_gateway_proto_depIdxs = []int32{
	2,  // 0: repogo.v1.preview_gateway.ClientMessage.hello:type_name -> repogo.v1.preview_gateway.DeviceHello
	6,  // 1: repogo.v1.preview_gateway.ClientMessage.http_response:type_name -> repogo.v1.preview_gateway.HttpResponse
	8,  // 2: repogo.v1.preview_gateway.ClientMessage.http_body_chunk:type_name -> repogo.v1.preview.PreviewBodyChunk
	7,  // 3: repogo.v1.preview_gateway.ClientMessage.ws_open_ack:type_name -> repogo.v1.preview_gateway.WsOpenAck
	9,  // 4: repogo.v1.preview_gateway.ClientMessage.ws_frame:type_name -> repogo.v1.preview.PreviewWsFrame
	10, // 5: repogo.v1.preview_gateway.ClientMessage.ws_close:type_name -> repogo.v1.preview.PreviewWsClose
	4,  // 6: repogo.v1.preview_gateway.ClientMessage.proof:type_name -> repogo.v1.preview_gateway.HostProof
	5,  // 7: repogo.v1.preview_gateway.ServerMessage.ready:type_name -> repogo.v1.preview_gateway.Ready
	11, // 8: repogo.v1.preview_gateway.ServerMessage.http_request:type_name -> repogo.v1.preview.PreviewRequest
	12, // 9: repogo.v1.preview_gateway.ServerMessage.ws_open:type_name -> repogo.v1.preview.PreviewWsOpen
	9,  // 10: repogo.v1.preview_gateway.ServerMessage.ws_frame:type_name -> repogo.v1.preview.PreviewWsFrame
	10, // 11: repogo.v1.preview_gateway.ServerMessage.ws_close:type_name -> repogo.v1.preview.PreviewWsClose
	3,  // 12: repogo.v1.preview_gateway.ServerMessage.challenge:type_name -> repogo.v1.preview_gateway.HostChallenge
	13, // 13: repogo.v1.preview_gateway.HttpResponse.response:type_name -> repogo.v1.preview.PreviewResponse
	14, // 14: repogo.v1.preview_gateway.WsOpenAck.ack:type_name -> repogo.v1.preview.PreviewWsOpenAck
	0,  // 15: repogo.v1.preview_gateway.PreviewGateway.Connect:input_type -> repogo.v1.preview_gateway.ClientMessage
	1,  // 16: repogo.v1.preview_gateway.PreviewGateway.Connect:output_type -> repogo.v1.preview_gateway.ServerMessage
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_repogo_v1_preview_gateway_proto_init() }
func file_repogo_v1_preview_gateway_proto_init() {
	if File_repogo_v1_preview_gateway_proto != nil {
		return
	}
	file_repogo_v1_preview_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_HttpResponse)(nil),
		(*ClientMessage_HttpBodyChunk)(nil),
		(*ClientMessage_WsOpenAck)(nil),
		(*ClientMessage_WsFrame)(nil),
		(*ClientMessage_WsClose)(nil),
		(*ClientMessage_Proof)(nil),
	}
	file_repogo_v1_preview_gateway_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Ready)(nil),
		(*ServerMessage_HttpRequest)(nil),
		(*ServerMessage_WsOpen)(nil),
		(*ServerMessage_WsFrame)(nil),
		(*ServerMessage_WsClose)(nil),
		(*ServerMessage_Challenge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repogo_v1_preview_gateway_proto_rawDesc), len(file_repogo_v1_preview_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repogo_v1_preview_gateway_proto_goTypes,
		DependencyIndexes: file_repogo_v1_preview_gateway_proto_depIdxs,
		MessageInfos:      file_repogo_v1_preview_gateway_proto_msgTypes,
	}.Build()
	File_repogo_v1_preview_gateway_proto = out.File
	file_repogo_v1_preview_gateway_proto_goTypes = nil
	file_repogo_v1_preview_gateway_proto_depIdxs = nil
}
