// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: repogo/v1/preview_gateway.proto

package previewgatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreviewGateway_Connect_FullMethodName = "/repogo.v1.preview_gateway.PreviewGateway/Connect"
)

// PreviewGatewayClient is the client API for PreviewGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Direct device → preview-gateway bidirectional stream.
//
// Replaces the previous gateway → broker → device routing for preview
// traffic. The Mac host (`apps/RepoGo Host`) dials the gateway directly,
// holds the stream open, and serves inbound HTTP / WebSocket requests
// against its localhost ports.
//
// Authorization is implicit in the Redis hostname registry:
//
//	apps/api (Firebase-authed) writes preview:hostname:<slug> → {userId,
//	deviceId, port, enabled}. The gateway looks up the slug at request
//	time and routes to whichever stream claimed (userId, deviceId). A
//	stream with no matching Redis row simply never receives traffic.
//
// The gateway does NOT verify Firebase ID tokens here; doing so would be
// redundant with apps/api's auth on the registry-write path. See
// .docs/gRPC/EVENTS.md for the broader event taxonomy and per-event semantics.
type PreviewGatewayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type previewGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPreviewGatewayClient(cc grpc.ClientConnInterface) PreviewGatewayClient {
	return &previewGatewayClient{cc}
}

func (c *previewGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewGateway_ServiceDesc.Streams[0], PreviewGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewGateway_ConnectClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// PreviewGatewayServer is the server API for PreviewGateway service.
// All implementations must embed UnimplementedPreviewGatewayServer
// for forward compatibility.
//
// Direct device → preview-gateway bidirectional stream.
//
// Replaces the previous gateway → broker → device routing for preview
// traffic. The Mac host (`apps/RepoGo Host`) dials the gateway directly,
// holds the stream open, and serves inbound HTTP / WebSocket requests
// against its localhost ports.
//
// Authorization is implicit in the Redis hostname registry:
//
//	apps/api (Firebase-authed) writes preview:hostname:<slug> → {userId,
//	deviceId, port, enabled}. The gateway looks up the slug at request
//	time and routes to whichever stream claimed (userId, deviceId). A
//	stream with no matching Redis row simply never receives traffic.
//
// The gateway does NOT verify Firebase ID tokens here; doing so would be
// redundant with apps/api's auth on the registry-write path. See
// .docs/gRPC/EVENTS.md for the broader event taxonomy and per-event semantics.
type PreviewGatewayServer interface {
	Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedPreviewGatewayServer()
}

// UnimplementedPreviewGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreviewGatewayServer struct{}

func (UnimplementedPreviewGatewayServer) Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPreviewGatewayServer) mustEmbedUnimplementedPreviewGatewayServer() {}
func (UnimplementedPreviewGatewayServer) testEmbeddedByValue()                        {}

// UnsafePreviewGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreviewGatewayServer will
// result in compilation errors.
type UnsafePreviewGatewayServer interface {
	mustEmbedUnimplementedPreviewGatewayServer()
}

func RegisterPreviewGatewayServer(s grpc.ServiceRegistrar, srv PreviewGatewayServer) {
	// If the following call panics, it indicates UnimplementedPreviewGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreviewGateway_ServiceDesc, srv)
}

func _PreviewGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewGatewayServer).Connect(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewGateway_ConnectServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// PreviewGateway_ServiceDesc is the grpc.ServiceDesc for PreviewGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreviewGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repogo.v1.preview_gateway.PreviewGateway",
	HandlerType: (*PreviewGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PreviewGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "repogo/v1/preview_gateway.proto",
}
