package emit_test

import (
	"flag"
	"regexp"
	"strings"
	"testing"

	// Producers register in init; each one the host emits from must be here
	// or the client is checked against a partial catalog.
	_ "github.com/repogo/host/internal/chatlive"
	_ "github.com/repogo/host/internal/environment"
	_ "github.com/repogo/host/internal/envsource"
	_ "github.com/repogo/host/internal/forward"
	_ "github.com/repogo/host/internal/hostinfo"
	_ "github.com/repogo/host/internal/hostsetup"
	_ "github.com/repogo/host/internal/mcp"
	_ "github.com/repogo/host/internal/projectwatch"
	_ "github.com/repogo/host/internal/repogomcp"
	_ "github.com/repogo/host/internal/rpc/devices"
	_ "github.com/repogo/host/internal/terminal"
	_ "github.com/repogo/host/internal/tunnel"

	"github.com/repogo/host/internal/emit"
	"github.com/repogo/host/internal/swiftcontract"
	"github.com/repogo/host/internal/testhost"
)

var update = flag.Bool("update", false, "rewrite docs/host-events.md and docs/events from the catalog")

const (
	docPath     = "../../docs/host-events.md"
	examplesDir = "../../docs/events"
	updateHint  = "run: go test ./internal/emit -update"
)

// The RepoGo iOS app and the packages it links, which live beside the host in
// this repo. Chat events are decoded in Packages/RepoGoKit/Sources/Transcript.
var clientDirs = []string{"../../../swift/repogo/repogo", "../../../swift/Packages"}

// Every event must be named by some client file as its family ("terminal") and
// bare method ("output") together, so a renamed event fails here, not in silence.
var swiftString = regexp.MustCompile(`"([a-z_]+(?:\.[a-z_]+)?)"`)

func TestClientHandlesEveryEvent(t *testing.T) {
	testhost.SkipWithoutClient(t, "../../../swift")
	host := map[string]bool{}
	for _, ev := range emit.Catalog() {
		host[ev.Method()] = true
	}
	if len(host) == 0 {
		t.Fatal("empty catalog: no producer registered")
	}

	// Environment status and the device list's change have no UI consumer yet;
	// their generated contracts are decoded in Swift tests.
	handled := map[string]bool{"environment.status": true, "devices.changed": true}
	testhost.SwiftSources(t, clientDirs, func(src []byte) {
		if strings.Contains(string(src), "// Generated by") {
			return
		}
		names := map[string]bool{}
		for _, m := range swiftString.FindAllSubmatch(src, -1) {
			names[string(m[1])] = true
		}
		for method := range host {
			family, bare, _ := strings.Cut(method, ".")
			eventType, generated := swiftcontract.EventExports[method]
			if generated && swiftcontract.EventFamilies[family] && strings.Contains(string(src), "HostAPI."+strings.Split(eventType, ".")[0]+".Event.self") || generated && strings.Contains(string(src), "HostAPI."+eventType+".self") || !generated && names[family] && names[bare] {
				handled[method] = true
			}
		}
	})

	for method := range host {
		if !handled[method] {
			t.Errorf("host emits %s but no file in %s names it", method, strings.Join(clientDirs, " or "))
		}
	}
}

// docs/host-events.md is the catalog for humans. It is generated, and the
// committed copy must match, so reading it is reading the code.
func TestDocMatchesCatalog(t *testing.T) {
	testhost.Golden(t, docPath, []byte(emit.Describe()), *update, updateHint)
}

// docs/events holds an example of every event, which RemoteTransport's tests
// decode with the app's types: the field-level half of the check above.
func TestExamplesMatchCatalog(t *testing.T) {
	want, err := emit.Examples()
	if err != nil {
		t.Fatal(err)
	}
	testhost.GoldenDir(t, examplesDir, want, *update, updateHint)
}

// Event payloads and their wire names come from the producers' catalog.
func TestSwiftEventsMatchCatalog(t *testing.T) {
	testhost.SkipWithoutClient(t, "../../../swift")
	testhost.Golden(t, "../../../swift/Packages/RemoteTransport/Sources/HostContract/HostEvents.swift", []byte(swiftcontract.Events(emit.Catalog())), *update, updateHint)
}
