package conformance_test

import (
	"encoding/json"
	"testing"

	"github.com/repogo/host/internal/repogomcp"
	"github.com/repogo/host/internal/testhost"
)

const swiftBrowserTool = "../../../../swift/Packages/RepoGit/Sources/LocalRPC/Generated/BrowserToolDefinition.swift"

// The phone's own agents offer the repogo MCP server's browser tool, so its
// name, description and schema are written from the host's.
func TestSwiftBrowserToolMatchesMCP(t *testing.T) {
	testhost.SkipWithoutClient(t, "../../../../swift")
	name, description, inputSchema := repogomcp.BrowserTool()
	schema, err := json.Marshal(inputSchema)
	if err != nil {
		t.Fatal(err)
	}
	src := "// Generated by `go test ./internal/rpc/conformance -update` in apps/host. Do not edit.\n\n" +
		"/// The repogo MCP server's browser tool, as the host's agents see it.\n" +
		"enum BrowserToolDefinition {\n" +
		"  static let name = " + swiftRawString(name) + "\n" +
		"  static let description = " + swiftRawString(description) + "\n" +
		"  static let parameters = " + swiftRawString(string(schema)) + "\n" +
		"}\n"
	testhost.Golden(t, swiftBrowserTool, []byte(src), *update, updateHint)
}

// swiftRawString is s as a Swift raw multi-line literal, which keeps it verbatim.
func swiftRawString(s string) string {
	return "####\"\"\"\n" + s + "\n\"\"\"####"
}
