package claude

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/repogo/host/internal/agent"
	"github.com/repogo/host/internal/session"
)

// The CLI writes its own bookkeeping into the transcript as user records. Every
// input here is a real line shape taken from ~/.claude/projects, because the
// filter is only worth what its patterns match.
func TestClaudeDropsSyntheticUserRecords(t *testing.T) {
	tests := []struct {
		name    string
		content any
		want    []string // expected user_message texts, in order
	}{
		{
			name:    "a real prompt survives",
			content: "So how do you think this should work?",
			want:    []string{"So how do you think this should work?"},
		},
		{
			name: "background task notification is dropped",
			content: "<task-notification>\n<task-id>bubl24ka6</task-id>\n" +
				"<status>completed</status>\n</task-notification>",
			want: nil,
		},
		{
			name:    "slash command invocation is dropped",
			content: "<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>",
			want:    nil,
		},
		{
			name:    "slash command output is dropped",
			content: "<local-command-stdout>Set model to Fable 5</local-command-stdout>",
			want:    nil,
		},
		{
			name:    "local command caveat is dropped",
			content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
			want:    nil,
		},
		{
			name:    "reminder appended to a prompt keeps the prompt",
			content: "<system-reminder>\n# Environment\nPlatform: darwin\n</system-reminder>Fix the scroll anchor",
			want:    []string{"Fix the scroll anchor"},
		},
		{
			name:    "a record that is only a reminder is dropped",
			content: "<system-reminder>Memory recalled: do not run builds.</system-reminder>",
			want:    nil,
		},
		{
			name:    "an unterminated reminder truncates rather than leaking",
			content: "Ship it<system-reminder>truncated mid-write",
			want:    []string{"Ship it"},
		},
		{
			name:    "mentioning a wrapper mid-sentence is still a real message",
			content: "why do I see <task-notification> blocks in my chats?",
			want:    []string{"why do I see <task-notification> blocks in my chats?"},
		},
		{
			name: "interrupts are dropped from text blocks",
			content: []map[string]any{
				{"type": "text", "text": "[Request interrupted by user]"},
			},
			want: nil,
		},
		{
			name: "interrupt for tool use is dropped too",
			content: []map[string]any{
				{"type": "text", "text": "[Request interrupted by user for tool use]"},
			},
			want: nil,
		},
		{
			name: "a real text block survives",
			content: []map[string]any{
				{"type": "text", "text": "keep this one"},
			},
			want: []string{"keep this one"},
		},
		// The shape a loaded skill actually arrives in: a text block in the user
		// turn, following the Skill tool_use, with no tag to distinguish it.
		{
			name: "a loaded skill body is dropped",
			content: []map[string]any{
				{"type": "text", "text": "Base directory for this skill: /Users/x/.claude/skills/add-rpc-method\n\n" +
					"# Adding or changing an RPC method\n\nSubject `rpc.<uid>.<deviceId>`"},
			},
			want: nil,
		},
		{
			name: "the CLI's note on a read image is dropped, the prompt kept",
			content: []map[string]any{
				{"type": "text", "text": "What's in this image [@a.jpg](file:///tmp/a.jpg)"},
				{"type": "text", "text": "[Image: source: /private/tmp/claude-501/x/images/1.jpg, original 943x2048, displayed at 921x2000.]"},
			},
			want: []string{"What's in this image [@a.jpg](file:///tmp/a.jpg)"},
		},
		{
			name:    "asking about a skill directory is a real message",
			content: "where is the base directory for this skill stored?",
			want:    []string{"where is the base directory for this skill stored?"},
		},
	}

	c := &Sessions{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			line, err := json.Marshal(map[string]any{
				"type":    "user",
				"message": map[string]any{"role": "user", "content": tt.content},
			})
			if err != nil {
				t.Fatal(err)
			}

			var got []string
			for _, e := range session.Parse(c, line) {
				if e.Kind == agent.EventUserMessage {
					got = append(got, e.Text)
				}
			}
			if len(got) != len(tt.want) {
				t.Fatalf("got %d user messages %q, want %d %q", len(got), got, len(tt.want), tt.want)
			}
			for i := range got {
				if got[i] != tt.want[i] {
					t.Errorf("message %d: got %q, want %q", i, got[i], tt.want[i])
				}
			}
		})
	}
}

// Tool results are the other half of an array-shaped user record and must not
// be swept up by a filter aimed at prose.
func TestClaudeKeepsToolResults(t *testing.T) {
	line, _ := json.Marshal(map[string]any{
		"type": "user",
		"message": map[string]any{"role": "user", "content": []map[string]any{
			{"type": "tool_result", "tool_use_id": "toolu_1", "content": "ok"},
		}},
	})

	events := session.Parse(&Sessions{}, line)
	if len(events) != 1 || events[0].Kind != agent.EventToolResult {
		t.Fatalf("got %+v, want one tool_result", events)
	}
	if events[0].Tool.CallID != "toolu_1" {
		t.Errorf("call id: got %q, want toolu_1", events[0].Tool.CallID)
	}
}

// A result that is a picture (Read on a PNG) reads "[image]", as Codex's does.
func TestClaudeImageToolResultIsNotBlank(t *testing.T) {
	line, _ := json.Marshal(map[string]any{
		"type": "user",
		"message": map[string]any{"role": "user", "content": []map[string]any{
			{"type": "tool_result", "tool_use_id": "toolu_1", "content": []map[string]any{
				{"type": "image", "source": map[string]any{"type": "base64", "media_type": "image/png", "data": "aGVsbG8="}},
			}},
		}},
	})

	events := session.Parse(&Sessions{}, line)
	if len(events) != 1 || events[0].Tool == nil || events[0].Tool.Output != "[image]" {
		t.Fatalf("got %+v, want one result reading [image]", events)
	}
}

// A transcript with no cwd names its directory only through Claude's encoding,
// where ".", "-" and "/" all read "-"; the directory on disk settles which.
func TestFindEncodedDirPrefersTheDirectoryOnDisk(t *testing.T) {
	root := t.TempDir()
	want := filepath.Join(root, "RepoGo", ".worktrees", "me", "repogo-v2", "main")
	if err := os.MkdirAll(want, 0o755); err != nil {
		t.Fatal(err)
	}
	// A near miss that the dash-to-slash reading would produce.
	if err := os.MkdirAll(filepath.Join(root, "RepoGo", ".worktrees", "me", "repogo"), 0o755); err != nil {
		t.Fatal(err)
	}

	got, ok := findEncodedDir(root, "RepoGo--worktrees-me-repogo-v2-main")
	if !ok || got != want {
		t.Fatalf("findEncodedDir = %q, %v; want %q", got, ok, want)
	}
	if _, ok := findEncodedDir(root, "RepoGo--worktrees-me-gone"); ok {
		t.Fatal("found a directory that does not exist")
	}
}
