package swiftcontract

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	hostemit "github.com/repogo/host/internal/emit"
	"github.com/repogo/host/internal/rpc"
	"github.com/repogo/host/internal/wiredoc"
)

// Serving generates the reverse direction of the named methods' and events'
// client types, for a phone-local host that decodes params and encodes results.
// Params decode as Go does: a missing field takes its zero value.
func Serving(specs []rpc.Spec, catalog []hostemit.Event, methods, events []string) string {
	g, eventGen, _ := methodsGen(specs)
	served := map[string]bool{}
	for _, name := range methods {
		if !methodExports[name] {
			panic("serving a method the client does not export: " + name)
		}
		served[name] = true
	}
	for _, name := range events {
		if _, ok := EventExports[name]; !ok {
			panic("serving an event the client does not export: " + name)
		}
		served[name] = true
	}
	need := map[string]int{}
	var visit func(t reflect.Type, name string, dir int)
	visit = func(t reflect.Type, name string, dir int) {
		if need[name]&dir != 0 {
			return
		}
		need[name] |= dir
		for _, f := range wiredoc.Fields(t) {
			field := f.Type
			for field.Kind() == reflect.Pointer || field.Kind() == reflect.Slice || field.Kind() == reflect.Array || field.Kind() == reflect.Map {
				field = field.Elem()
			}
			if field.Kind() == reflect.Struct && field != timeT {
				visit(field, g.names[field], dir)
			}
		}
	}
	for _, s := range specs {
		if !served[s.Name] {
			continue
		}
		split := strings.LastIndexByte(s.Name, '.')
		visit(s.Params, swiftFamily(s.Name[:split])+"."+pascal(s.Name[split+1:])+"Params", decodes)
		visit(s.Result, g.names[s.Result], encodes)
	}
	for _, ev := range catalog {
		if name, ok := EventExports[ev.Method()]; ok && served[ev.Method()] {
			visit(reflect.TypeOf(ev), name, encodes)
		}
	}

	names := make([]string, 0, len(need))
	for name := range need {
		names = append(names, name)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString("// Generated by `go test ./internal/rpc/conformance -update` in apps/host. Do not edit.\n\nimport Foundation\nimport HostContract\n")
	for _, name := range names {
		// The event file owns a shared snapshot's client shape.
		owner := g
		if _, ok := eventGen.props[name]; ok {
			owner = eventGen
		}
		props, ok := owner.props[name]
		if !ok {
			panic("no generated client type for " + name)
		}
		has := map[string]int{"Codable": encodes | decodes, "Encodable": encodes, "Decodable": decodes}[owner.conformances[name]]
		missing := need[name] &^ has
		if missing&decodes != 0 {
			b.WriteString(servingDecoder(name, props))
		}
		if missing&encodes != 0 {
			b.WriteString(servingEncoder(name, props))
		}
	}
	b.WriteString(servingKey)
	return b.String()
}

func servingDecoder(name string, props []prop) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\nextension HostAPI.%s: @retroactive Decodable {\n  public init(from decoder: Decoder) throws {\n", name)
	if len(props) == 0 {
		b.WriteString("    self.init()\n  }\n}\n")
		return b.String()
	}
	b.WriteString("    let c = try decoder.container(keyedBy: WireKey.self)\n    self.init(\n")
	for i, p := range props {
		ty := strings.TrimSuffix(p.ty, "?")
		switch {
		case p.optional:
			fmt.Fprintf(&b, "      %s: try c.decodeIfPresent(%s.self, forKey: %q)", p.swift, ty, p.json)
		case strings.HasPrefix(ty, "HostAPI."):
			// An object has no Swift zero value to stand in for a missing one, so it is required.
			fmt.Fprintf(&b, "      %s: try c.decode(%s.self, forKey: %q)", p.swift, ty, p.json)
		default:
			fmt.Fprintf(&b, "      %s: try c.decodeIfPresent(%s.self, forKey: %q) ?? %s", p.swift, ty, p.json, swiftZero(ty))
		}
		if i < len(props)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("    )\n  }\n}\n")
	return b.String()
}

func servingEncoder(name string, props []prop) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\nextension HostAPI.%s: @retroactive Encodable {\n  public func encode(to encoder: Encoder) throws {\n", name)
	if len(props) == 0 {
		b.WriteString("    _ = encoder.container(keyedBy: WireKey.self)\n  }\n}\n")
		return b.String()
	}
	b.WriteString("    var c = encoder.container(keyedBy: WireKey.self)\n")
	for _, p := range props {
		// Go sends a nil field without omitempty as null; only an omitempty one is left out.
		op := "encode"
		if p.optional && p.omitted {
			op = "encodeIfPresent"
		}
		fmt.Fprintf(&b, "    try c.%s(%s, forKey: %q)\n", op, p.swift, p.json)
	}
	b.WriteString("  }\n}\n")
	return b.String()
}

// swiftZero is the Swift spelling of a Go zero value.
func swiftZero(ty string) string {
	switch {
	case ty == "String":
		return `""`
	case ty == "Bool":
		return "false"
	case ty == "Int" || ty == "Int64" || ty == "Double":
		return "0"
	case ty == "Data":
		return "Data()"
	case strings.HasPrefix(ty, "[String: "):
		return "[:]"
	case strings.HasPrefix(ty, "["):
		return "[]"
	}
	panic("no Go zero value for Swift type " + ty)
}

const servingKey = `
private struct WireKey: CodingKey, ExpressibleByStringLiteral {
  let stringValue: String
  var intValue: Int? { nil }
  init(stringLiteral value: String) { stringValue = value }
  init?(stringValue: String) { self.stringValue = stringValue }
  init?(intValue: Int) { nil }
}
`
