// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: repogo/v1/preview.proto

package previewv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsFrameType int32

const (
	WsFrameType_WS_FRAME_TYPE_UNSPECIFIED WsFrameType = 0
	WsFrameType_WS_FRAME_TYPE_TEXT        WsFrameType = 1
	WsFrameType_WS_FRAME_TYPE_BINARY      WsFrameType = 2
	WsFrameType_WS_FRAME_TYPE_PING        WsFrameType = 3
	WsFrameType_WS_FRAME_TYPE_PONG        WsFrameType = 4
)

// Enum value maps for WsFrameType.
var (
	WsFrameType_name = map[int32]string{
		0: "WS_FRAME_TYPE_UNSPECIFIED",
		1: "WS_FRAME_TYPE_TEXT",
		2: "WS_FRAME_TYPE_BINARY",
		3: "WS_FRAME_TYPE_PING",
		4: "WS_FRAME_TYPE_PONG",
	}
	WsFrameType_value = map[string]int32{
		"WS_FRAME_TYPE_UNSPECIFIED": 0,
		"WS_FRAME_TYPE_TEXT":        1,
		"WS_FRAME_TYPE_BINARY":      2,
		"WS_FRAME_TYPE_PING":        3,
		"WS_FRAME_TYPE_PONG":        4,
	}
)

func (x WsFrameType) Enum() *WsFrameType {
	p := new(WsFrameType)
	*p = x
	return p
}

func (x WsFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_repogo_v1_preview_proto_enumTypes[0].Descriptor()
}

func (WsFrameType) Type() protoreflect.EnumType {
	return &file_repogo_v1_preview_proto_enumTypes[0]
}

func (x WsFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsFrameType.Descriptor instead.
func (WsFrameType) EnumDescriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{0}
}

// handled_by: HOST, SANDBOX
// caller: SERVICE (apps/preview-gateway-fly) on the gateway path;
//
//	USER on the `preview.fetch` / `preview.pipe_open` device RPCs
type PreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // gateway-minted; correlates streaming responses
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"` // port ("3000") OR host ("web.localhost"[:port]); device resolves
	HeaderLines   []string               `protobuf:"bytes,5,rep,name=header_lines,json=headerLines,proto3" json:"header_lines,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_repogo_v1_preview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreviewRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PreviewRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PreviewRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PreviewRequest) GetHeaderLines() []string {
	if x != nil {
		return x.HeaderLines
	}
	return nil
}

func (x *PreviewRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Returned via Emit Ack for buffered responses. For streaming responses,
// `body` is empty and `streaming = true`; chunks follow via push events
// addressed to the gateway's room.
type PreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	HeaderLines   []string               `protobuf:"bytes,2,rep,name=header_lines,json=headerLines,proto3" json:"header_lines,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Streaming     bool                   `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"` // if true, body chunks follow as preview.body_chunk events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_repogo_v1_preview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PreviewResponse) GetHeaderLines() []string {
	if x != nil {
		return x.HeaderLines
	}
	return nil
}

func (x *PreviewResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PreviewResponse) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

// Pushed from the device to the gateway when streaming a response body.
// Gateway path only — the device-RPC `fetch` is buffered, and its pipe lane
// carries raw bytes rather than this message.
//
// handled_by: SERVICE (gateway)
// caller: HOST, SANDBOX
type PreviewBodyChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	EndOfStream   bool                   `protobuf:"varint,3,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"` // last chunk; gateway closes the response stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewBodyChunk) Reset() {
	*x = PreviewBodyChunk{}
	mi := &file_repogo_v1_preview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewBodyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewBodyChunk) ProtoMessage() {}

func (x *PreviewBodyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewBodyChunk.ProtoReflect.Descriptor instead.
func (*PreviewBodyChunk) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewBodyChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreviewBodyChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PreviewBodyChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

// handled_by: HOST, SANDBOX
// caller: SERVICE (gateway)
//
// Gateway path only. The device-RPC family upgrades with `pipe_open`, which
// reuses `PreviewRequest` so the browser's original upgrade request replays
// byte-for-byte.
//
// Device opens a WS to ws://<target><path>, negotiates the same
// subprotocols + headers the browser sent, and tracks it under
// session_id. Inbound frames from the local WS get pushed back as
// preview.ws_frame events to caller_room.
type PreviewWsOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // port ("3000") OR host ("web.localhost"[:port]); device resolves
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	HeaderLines   []string               `protobuf:"bytes,4,rep,name=header_lines,json=headerLines,proto3" json:"header_lines,omitempty"` // forwarded HTTP headers (Cookie, Origin, etc.)
	Subprotocols  []string               `protobuf:"bytes,5,rep,name=subprotocols,proto3" json:"subprotocols,omitempty"`                  // Sec-WebSocket-Protocol values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewWsOpen) Reset() {
	*x = PreviewWsOpen{}
	mi := &file_repogo_v1_preview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewWsOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewWsOpen) ProtoMessage() {}

func (x *PreviewWsOpen) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewWsOpen.ProtoReflect.Descriptor instead.
func (*PreviewWsOpen) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewWsOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreviewWsOpen) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PreviewWsOpen) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PreviewWsOpen) GetHeaderLines() []string {
	if x != nil {
		return x.HeaderLines
	}
	return nil
}

func (x *PreviewWsOpen) GetSubprotocols() []string {
	if x != nil {
		return x.Subprotocols
	}
	return nil
}

// Returned via Ack on preview.ws_open. If status != 0, gateway closes the
// client WS with that close code.
type PreviewWsOpenAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AcceptedSubprotocol string                 `protobuf:"bytes,1,opt,name=accepted_subprotocol,json=acceptedSubprotocol,proto3" json:"accepted_subprotocol,omitempty"` // server-chosen subprotocol; empty if none
	CloseCode           uint32                 `protobuf:"varint,2,opt,name=close_code,json=closeCode,proto3" json:"close_code,omitempty"`                              // 0 = open succeeded; otherwise close client with this code
	CloseReason         string                 `protobuf:"bytes,3,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PreviewWsOpenAck) Reset() {
	*x = PreviewWsOpenAck{}
	mi := &file_repogo_v1_preview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewWsOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewWsOpenAck) ProtoMessage() {}

func (x *PreviewWsOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewWsOpenAck.ProtoReflect.Descriptor instead.
func (*PreviewWsOpenAck) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{4}
}

func (x *PreviewWsOpenAck) GetAcceptedSubprotocol() string {
	if x != nil {
		return x.AcceptedSubprotocol
	}
	return ""
}

func (x *PreviewWsOpenAck) GetCloseCode() uint32 {
	if x != nil {
		return x.CloseCode
	}
	return 0
}

func (x *PreviewWsOpenAck) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

// Bidi: gateway → device (browser sent a frame), or device → gateway
// (local server sent a frame). caller_room on the inbound side tells the
// device which gateway instance to push back to.
//
// handled_by: HOST, SANDBOX (gateway → device) OR SERVICE (device → gateway)
// caller: SERVICE on the gateway path; USER on `preview.pipe_send`, where
//
//	`data` is opaque bytes and `type` is unused
type PreviewWsFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          WsFrameType            `protobuf:"varint,2,opt,name=type,proto3,enum=repogo.v1.preview.WsFrameType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewWsFrame) Reset() {
	*x = PreviewWsFrame{}
	mi := &file_repogo_v1_preview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewWsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewWsFrame) ProtoMessage() {}

func (x *PreviewWsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewWsFrame.ProtoReflect.Descriptor instead.
func (*PreviewWsFrame) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{5}
}

func (x *PreviewWsFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreviewWsFrame) GetType() WsFrameType {
	if x != nil {
		return x.Type
	}
	return WsFrameType_WS_FRAME_TYPE_UNSPECIFIED
}

func (x *PreviewWsFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Either direction. Closing the WS for that session_id.
// handled_by: HOST, SANDBOX OR SERVICE
// caller: SERVICE on the gateway path; USER on `preview.pipe_close`, where
//
//	only `session_id` is read
type PreviewWsClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` // RFC 6455 close code
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewWsClose) Reset() {
	*x = PreviewWsClose{}
	mi := &file_repogo_v1_preview_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewWsClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewWsClose) ProtoMessage() {}

func (x *PreviewWsClose) ProtoReflect() protoreflect.Message {
	mi := &file_repogo_v1_preview_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewWsClose.ProtoReflect.Descriptor instead.
func (*PreviewWsClose) Descriptor() ([]byte, []int) {
	return file_repogo_v1_preview_proto_rawDescGZIP(), []int{6}
}

func (x *PreviewWsClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreviewWsClose) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PreviewWsClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_repogo_v1_preview_proto protoreflect.FileDescriptor

const file_repogo_v1_preview_proto_rawDesc = "" +
	"\n" +
	"\x17repogo/v1/preview.proto\x12\x11repogo.v1.preview\"\xaa\x01\n" +
	"\x0ePreviewRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12!\n" +
	"\fheader_lines\x18\x05 \x03(\tR\vheaderLines\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\"~\n" +
	"\x0fPreviewResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12!\n" +
	"\fheader_lines\x18\x02 \x03(\tR\vheaderLines\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\"i\n" +
	"\x10PreviewBodyChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\"\n" +
	"\rend_of_stream\x18\x03 \x01(\bR\vendOfStream\"\xa1\x01\n" +
	"\rPreviewWsOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\fheader_lines\x18\x04 \x03(\tR\vheaderLines\x12\"\n" +
	"\fsubprotocols\x18\x05 \x03(\tR\fsubprotocols\"\x87\x01\n" +
	"\x10PreviewWsOpenAck\x121\n" +
	"\x14accepted_subprotocol\x18\x01 \x01(\tR\x13acceptedSubprotocol\x12\x1d\n" +
	"\n" +
	"close_code\x18\x02 \x01(\rR\tcloseCode\x12!\n" +
	"\fclose_reason\x18\x03 \x01(\tR\vcloseReason\"w\n" +
	"\x0ePreviewWsFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.repogo.v1.preview.WsFrameTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"[\n" +
	"\x0ePreviewWsClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*\x8e\x01\n" +
	"\vWsFrameType\x12\x1d\n" +
	"\x19WS_FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WS_FRAME_TYPE_TEXT\x10\x01\x12\x18\n" +
	"\x14WS_FRAME_TYPE_BINARY\x10\x02\x12\x16\n" +
	"\x12WS_FRAME_TYPE_PING\x10\x03\x12\x16\n" +
	"\x12WS_FRAME_TYPE_PONG\x10\x04BGZEgithub.com/repogo/preview-gateway-fly/gen/repogo/v1/preview;previewv1b\x06proto3"

var (
	file_repogo_v1_preview_proto_rawDescOnce sync.Once
	file_repogo_v1_preview_proto_rawDescData []byte
)

func file_repogo_v1_preview_proto_rawDescGZIP() []byte {
	file_repogo_v1_preview_proto_rawDescOnce.Do(func() {
		file_repogo_v1_preview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repogo_v1_preview_proto_rawDesc), len(file_repogo_v1_preview_proto_rawDesc)))
	})
	return file_repogo_v1_preview_proto_rawDescData
}

var file_repogo_v1_preview_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repogo_v1_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_repogo_v1_preview_proto_goTypes = []any{
	(WsFrameType)(0),         // 0: repogo.v1.preview.WsFrameType
	(*PreviewRequest)(nil),   // 1: repogo.v1.preview.PreviewRequest
	(*PreviewResponse)(nil),  // 2: repogo.v1.preview.PreviewResponse
	(*PreviewBodyChunk)(nil), // 3: repogo.v1.preview.PreviewBodyChunk
	(*PreviewWsOpen)(nil),    // 4: repogo.v1.preview.PreviewWsOpen
	(*PreviewWsOpenAck)(nil), // 5: repogo.v1.preview.PreviewWsOpenAck
	(*PreviewWsFrame)(nil),   // 6: repogo.v1.preview.PreviewWsFrame
	(*PreviewWsClose)(nil),   // 7: repogo.v1.preview.PreviewWsClose
}
var file_repogo_v1_preview_proto_depIdxs = []int32{
	0, // 0: repogo.v1.preview.PreviewWsFrame.type:type_name -> repogo.v1.preview.WsFrameType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_repogo_v1_preview_proto_init() }
func file_repogo_v1_preview_proto_init() {
	if File_repogo_v1_preview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repogo_v1_preview_proto_rawDesc), len(file_repogo_v1_preview_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repogo_v1_preview_proto_goTypes,
		DependencyIndexes: file_repogo_v1_preview_proto_depIdxs,
		EnumInfos:         file_repogo_v1_preview_proto_enumTypes,
		MessageInfos:      file_repogo_v1_preview_proto_msgTypes,
	}.Build()
	File_repogo_v1_preview_proto = out.File
	file_repogo_v1_preview_proto_goTypes = nil
	file_repogo_v1_preview_proto_depIdxs = nil
}
